### ISSUE TITLE
Package not available

### ISSUE THREAD

**Issue by jwillikers** [matrix-org/eslint-plugin-matrix-org#16]
**Describe the bug**
Follow the instructions in the README to add the project and it fails.

```
$ yarn add eslint-plugin-matrix-org --dev
yarn add v1.22.10
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/eslint-plugin-matrix-org: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/user/Projects/element-web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**To Reproduce**
1. `yarn add eslint-plugin-matrix-org --dev`

**Expected behavior**
The package should have been added as a dependency as described in the README.

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 34

**Comment by jryans** [comment]
Hmm, yeah for the moment, we're using this from Git directly. Those install instructions were incorrectly carried over from the previous package name.

If it would be useful to others, perhaps we should resume publishing it after all...?

**Comment by fnwbr** [comment]
Any updates on this? We'd like to use your linter config for Matrix-related projects over at @medienhaus...

**Comment by jryans** [comment]
It is now available once more: https://www.npmjs.com/package/eslint-plugin-matrix-org
